### PR TITLE
added some quality of life things ...

### PR DESCRIPTION
**Pull request by Notliam99**
WHY DO U HAVE A WEBPACK GH ACTION litraly makes zero sense i added the requried packages for it to work but  why. other wise i added to the readme and added a start script

### CODE REVIEW

**Comment by Ellozac** [comment]
I didn't know wat it did I was looking through them then added it and
forgot about it

**Comment by Notliam99** [comment]
Hi I updated and removed webpack so now the action just runs the file and checks for a runtime error

**Comment by Notliam99** [comment]
Don't merge idk the runner failed give me a hot minute

**Comment by Notliam99** [comment]
OH it works it now can test ur code 👍🏿 👍🏿 👍🏿 
# PLZ MERGE !!!

**Comment by Ellozac** [comment]
Ok, thanks.

**Pull request merged**
